Employee-Leave-Management-System.Web/Controllers/LeaveTypesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Employee_Leave_Management_System.Web.Data.Entities;
using AutoMapper;
using Employee_Leave_Management_System.Web.Models.Dtos;
using Employee_Leave_Management_System.Web.Contracts;
using Microsoft.AspNetCore.Authorization;
using Employee_Leave_Management_System.Web.Constants;

namespace Employee_Leave_Management_System.Web.Controllers
{
	[Authorize(Roles = Roles.ADMINISTRATOR)]
	public class LeaveTypesController : Controller
	{
		private readonly ILeaveTypeRepository _leaveTypeRepository;
		private readonly IMapper _mapper;

		public LeaveTypesController(ILeaveTypeRepository leaveTypeRepository, IMapper mapper)
		{
			_leaveTypeRepository = leaveTypeRepository;
			_mapper = mapper;
		}

		public async Task<IActionResult> Index()
		{
			var modelDtos = _mapper.Map<List<LeaveTypeDto>>(await _leaveTypeRepository.GetAllAsync());
			return View(modelDtos);
		}

		public async Task<IActionResult> Details(int? id)
		{
			var leaveType = await _leaveTypeRepository.GetAsync(id);
			if (leaveType == null)
			{
				return NotFound();
			}
			var leaveTypeDto = _mapper.Map<LeaveTypeDto>(leaveType);
			return View(leaveTypeDto);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(LeaveTypeDto leaveTypeDto)
		{
			if (ModelState.IsValid)
			{
				var leaveTypeEntity = _mapper.Map<LeaveType>(leaveTypeDto);
				await _leaveTypeRepository.AddAsync(leaveTypeEntity);
				return RedirectToAction(nameof(Index));
			}
			return View(leaveTypeDto);
		}

		public async Task<IActionResult> Edit(int? id)
		{
			var leaveType = await _leaveTypeRepository.GetAsync(id);
			if (leaveType == null)
			{
				return NotFound();
			}
			var leaveTypeDto = _mapper.Map<LeaveTypeDto>(leaveType);
			return View(leaveTypeDto);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, LeaveTypeDto leaveTypeDto)
		{
			if (id != leaveTypeDto.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					var leaveTypeEntity = _mapper.Map<LeaveType>(leaveTypeDto);
					await _leaveTypeRepository.UpdateAsync(leaveTypeEntity);
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!await _leaveTypeRepository.Exists(leaveTypeDto.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(leaveTypeDto);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await _leaveTypeRepository.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}
	}
}

Employee-Leave-Management-System.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Employee_Leave_Management_System.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" />
	<link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Employee-Leave-Management-System.Web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Employee Leave Management System</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between container">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="" asp-action="">Apply for leave</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-white" asp-area="" asp-controller="" asp-action="">My leave</a>
						</li>
						@if (User.IsInRole(Roles.ADMINISTRATOR))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Leave Management
								</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
									<li><a class="dropdown-item" asp-controller="LeaveTypes" asp-action="Index">Leave Types</a></li>
									<li><a class="dropdown-item" href="#">Leave Allocations</a></li>
									<li><a class="dropdown-item" href="#">Leave Requests</a></li>
									<li><a class="dropdown-item" href="#">Employee Management</a></li>
								</ul>
							</li>
						}
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; @DateTime.Now.Year - Employee Leave Management System - <a asp-area="" asp-controller="Home" asp-action="Index">Index</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/sweetalert/sweetalert.min.js"></script>
	<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>